module Errors where
------------------ERRORS-------------------------------------
assignement = "incompatible type in assignment."
index = "incompatible index element type."
value = "incompatible value type."
noVariable = "no such variable." 
int = "Int type required."
wrongReturn = "wrong return type."
wrongCondition = "wrong condition type."
and = "logical operator (&&)."
or = "logical operator (||)."
noMethod = "no such method."
functionArgument = "wrong argument type."
memoryCorrupt = "Memory corrupt."
argumentsNumber = "wrong number of arguments."
noReturn = "no return statement"
add = "only Str and Str or Int and Int can be added."
bool = "Boolean type required in"
comparison = "incompatible type."
declared = "variable was already declared."
declaredParameter = "arguments cannot have the same name."
